name: Continuous Delivery

on:
  push:
    branches:
      - main
    tags:
      - 'v*'           # Run on tags starting with "v", e.g. v1.0, v2.1.3 etc.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean verify

      - name: Deploy to Jenkins Maven repo
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
        run: |
          mvn deploy -DskipTests \
            -Dmaven.repo.remote=https://repo.jenkins-ci.org/releases/ \
            -Dmaven.username=$MAVEN_USERNAME \
            -Dmaven.password=$MAVEN_TOKEN
