# Jenkins Plugin CD workflow for fork testing
# - Runs validate + release on manual dispatch
# - skip_publish ensures no artifacts are actually published
# - Safe for forks, does not require real MAVEN credentials

name: cd
on:
  workflow_dispatch:
    inputs:
      validate_only:
        required: false
        type: boolean
        description: Run validation only (skip release)
        default: false

permissions:
  checks: read
  contents: write

jobs:
  maven-cd:
    uses: jenkins-infra/github-reusable-workflows/.github/workflows/maven-cd.yml@v1
    with:
      validate_only: false     # force release step
      skip_publish: true       # do not actually publish HPI
    secrets:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME || 'dummy' }}
      MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN || 'dummy' }}